Repository ferraridamiano/ConverterNOW, pull requests merged in 2021-04, with the labels that each got.

#78 Create app_es.arb, update Spanish translation
  lib/l10n/app_es.arb
  lib/main.dart
Labels: good first contribution, translations

#79 Create es-ES dir, create short/full desc files.
  fastlane/metadata/android/es-ES/full_description.txt
  fastlane/metadata/android/es-ES/short_description.txt
Labels: translations

#80 New desktop layout
  lib/helpers/responsive_helper.dart
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_it.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_pt.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_tr.arb
  lib/main.dart
  lib/models/AppModel.dart
  lib/pages/AppManager.dart
  lib/pages/CalculatorWidget.dart
  lib/pages/ConversionPage.dart
  lib/styles/consts.dart
  pubspec.yaml
  resources/images/calculator.png
Labels: UI, linux-platform, web-platform

#82 Implementing the ECB API
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_it.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_pt.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_tr.arb
  lib/models/Conversions.dart
  lib/pages/ConversionPage.dart
  lib/utils/PropertyUnitList.dart
  lib/utils/Utils.dart
Labels: fix
