Repository ferraridamiano/ConverterNOW, pull requests merged in 2021-03, with the labels that each got.

#67 Update Russian full description 👍🏻
  fastlane/metadata/android/ru-RU/full_description.txt
Labels: translations

#66 Update russian translate 😄
  lib/l10n/app_ru.arb
Labels: translations

#69 Update app_en.arb to use ISO 4217 currency names
  lib/l10n/app_en.arb
Labels: good first contribution, typo

#71 Turkish translations added
  fastlane/metadata/android/tr-TR/changelogs/24.txt
  fastlane/metadata/android/tr-TR/changelogs/25.txt
  fastlane/metadata/android/tr-TR/changelogs/26.txt
  fastlane/metadata/android/tr-TR/changelogs/27.txt
  fastlane/metadata/android/tr-TR/full_description.txt
  fastlane/metadata/android/tr-TR/short_description.txt
  lib/l10n/app_tr.arb
  lib/main.dart
Labels: good first contribution, translations

#72 Adjusted the translation of currencies
  lib/l10n/app_de.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_it.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_pt.arb
  lib/l10n/app_ru.arb
Labels: translations, typo

#73 Calculator improvements
  .github/workflows/tests.yml
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_fr.arb
  lib/l10n/app_it.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_pt.arb
  lib/l10n/app_ru.arb
  lib/models/Calculator.dart
  lib/pages/Calculator.dart
  lib/pages/CalculatorWidget.dart
  lib/pages/ConversionPage.dart
  pubspec.yaml
  test/calculator_test.dart
Labels: General improvement, enhancement
